import { IkonIcon } from "~/assets/img"
import background from "~/assets/img/imgbg.png"
import pic from "~/assets/img/Ikon.png"

export const dummyObj = [
  {
    id: 1,
    apartmentImg: background,
    apartmentName: 'Modern loft apartment',
    status: 'SALE',
    featured:true,
    price: '860000',
    address: 'Nwaniba Road, Uyo. Akwa Ibom State',
    propertyType: 'Apartment',
    bedNo: '1',
    toiletNo: '2',
    showerNo: '2',
    carNo: '0',
    photoNo: '22',
    agentImg: pic,
    agentName: 'The Goat',
    date: '2 days ago' 
  },
  {
    id: 2,
    apartmentImg: background,
    apartmentName: 'Modern loft apartment',
    status: 'RENT',
    featured: true,
    price: '860000',
    address: 'Nwaniba Road, Uyo. Akwa Ibom State',
    propertyType: 'Apartment',
    bedNo: '3',
    toiletNo: '2',
    showerNo: '2',
    carNo: '0',
    photoNo: '22',
    agentImg: IkonIcon,
    agentName: 'The Goat',
    date: '2 days ago' 
  },
  {
    id: 3,
    apartmentImg: background,
    apartmentName: 'Modern loft apartment',
    status: 'SALE',
    featured: true,
    price: '860000',
    address: 'Nwaniba Road, Uyo. Akwa Ibom State',
    propertyType: 'Apartment',
    bedNo: '0',
    toiletNo: '2',
    showerNo: '2',
    carNo: '0',
    photoNo: '22',
    agentImg: IkonIcon,
    agentName: 'The Goat',
    date: '2 days ago' 
  },
  {
    id: 4,
    apartmentImg: background,
    apartmentName: 'Modern loft apartment',
    status: 'RENT',
    featured: true,
    price: '860000',
    address: 'Nwaniba Road, Uyo. Akwa Ibom State',
    propertyType: 'Apartment',
    bedNo: '3',
    toiletNo: '1',
    showerNo: '2',
    carNo: '3',
    photoNo: '22',
    agentImg: IkonIcon,
    agentName: 'The Goat',
    date: '2 days ago' 
  },
  {
    id: 5,
    apartmentImg: background,
    apartmentName: 'Modern loft apartment',
    status: 'SALE',
    featured: true,
    price: '860000',
    address: 'Nwaniba Road, Uyo. Akwa Ibom State',
    propertyType: 'Apartment',
    bedNo: '3',
    toiletNo: '2',
    showerNo: '2',
    carNo: '0',
    photoNo: '22',
    agentImg: IkonIcon,
    agentName: 'The Goat',
    date: '2 days ago' 
  },
  {
    id: 6,
    apartmentImg: background,
    apartmentName: 'Modern loft apartment',
    status: 'RENT',
    featured: true,
    price: '860000',
    address: 'Nwaniba Road, Uyo. Akwa Ibom State',
    propertyType: 'Apartment',
    bedNo: '3',
    toiletNo: '2',
    showerNo: '2',
    carNo: '0',
    photoNo: '22',
    agentImg: IkonIcon,
    agentName: 'The Goat',
    date: '2 days ago' 
  },
]