import Ikon from "~/assets/Ikon.png";
import background from "~/assets/imgbg.png"

export const dummyObj = [
  {
    apartmentImg: background,
    apartmentName: 'Modern loft apartment',
    status: 'SALE',
    featured: 'FEATURED',
    price: '86000000',
    address: 'Nwaniba Road, Uyo. Akwa Ibom State',
    propertyType: 'Apartment',
    bedNo: '3',
    toiletNo: '2',
    showerNo: '2',
    carNo: '0',
    agentImg: Ikon,
    agentName: 'The Goat',
    date: '2 days ago' 
  },
  {
    apartmentImg: background,
    apartmentName: 'Modern loft apartment',
    status: 'RENT',
    featured: 'FEATURED',
    price: '86000000',
    address: 'Nwaniba Road, Uyo. Akwa Ibom State',
    propertyType: 'Apartment',
    bedNo: '3',
    toiletNo: '2',
    showerNo: '2',
    carNo: '0',
    agentImg: Ikon,
    agentName: 'The Goat',
    date: '2 days ago' 
  },
  {
    apartmentImg: background,
    apartmentName: 'Modern loft apartment',
    status: 'SALE',
    featured: 'FEATURED',
    price: '86000000',
    address: 'Nwaniba Road, Uyo. Akwa Ibom State',
    propertyType: 'Apartment',
    bedNo: '3',
    toiletNo: '2',
    showerNo: '2',
    carNo: '0',
    agentImg: Ikon,
    agentName: 'The Goat',
    date: '2 days ago' 
  },
  {
    apartmentImg: background,
    apartmentName: 'Modern loft apartment',
    status: 'RENT',
    featured: 'FEATURED',
    price: '86000000',
    address: 'Nwaniba Road, Uyo. Akwa Ibom State',
    propertyType: 'Apartment',
    bedNo: '3',
    toiletNo: '2',
    showerNo: '2',
    carNo: '0',
    agentImg: Ikon,
    agentName: 'The Goat',
    date: '2 days ago' 
  },
  {
    apartmentImg: background,
    apartmentName: 'Modern loft apartment',
    status: 'SALE',
    featured: 'FEATURED',
    price: '86000000',
    address: 'Nwaniba Road, Uyo. Akwa Ibom State',
    propertyType: 'Apartment',
    bedNo: '3',
    toiletNo: '2',
    showerNo: '2',
    carNo: '0',
    agentImg: Ikon,
    agentName: 'The Goat',
    date: '2 days ago' 
  },
  {
    apartmentImg: background,
    apartmentName: 'Modern loft apartment',
    status: 'RENT',
    featured: 'FEATURED',
    price: '86000000',
    address: 'Nwaniba Road, Uyo. Akwa Ibom State',
    propertyType: 'Apartment',
    bedNo: '3',
    toiletNo: '2',
    showerNo: '2',
    carNo: '0',
    agentImg: Ikon,
    agentName: 'The Goat',
    date: '2 days ago' 
  },
]