import logo from "./Logo.svg";
import arrow from "./arrow.svg";
import house_1 from "./house.svg";
import house_2 from "./house_2.svg";
import house_3 from "./house_3.svg";
import agents from "./agents.svg";
import agencies from "./agencies.svg";
import aboutUs from "./about_us.svg";
import contactUs from "./messages.svg";
import faq from "./faq.svg";
import frame from "./Frame.svg";

export const logoIcon = `${logo}#img`;
export const arrowIcon = `${arrow}#img`;
export const house_1Icon = `${house_1}#img`;
export const house_2Icon = `${house_2}#img`;
export const house_3Icon = `${house_3}#img`;
export const agentsIcon = `${agents}#img`;
export const agenciesIcon = `${agencies}#img`;
export const aboutUsIcon = `${aboutUs}#img`;
export const contactUsIcon = `${contactUs}#img`;
export const faqIcon = `${faq}#img`;
export const frameIcon = `${frame}#img`; 